[workspace]

members = [
    "advent_of_code_common",
    "advent_of_code_inputs",
    "advent_of_code_results",
    "advent_of_code_2024",
    "advent_of_code_2025",
    "advent_of_code_scripts",
]
resolver = "3"
